package br.com.infox.telas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

public class TelaOS extends javax.swing.JInternalFrame {

	private static Connection connection;
	private PreparedStatement preparedStatement;
	private ResultSet resultSet;
	private ResultSetMetaData resultSetMetaData;

	/**
	 * Creates new form TelaOS
	 */
	public TelaOS() {
		initComponents();
	}

	public static void setValues(PreparedStatement ps, Object... values) throws SQLException {
		for (int i = 0; i < values.length; i++) {
			ps.setObject(i + 1, values[i]);
		}
	}

	public static void printSQLException(SQLException ex) {
		for (Throwable e : ex) {
			if (e instanceof SQLException) {
				System.err.println("SQLState: " + ((SQLException) e).getSQLState());
				System.err.println("Error Code: " + ((SQLException) e).getErrorCode());
				System.err.println("Message: " + e.getMessage());
				e.printStackTrace(System.err);
				Throwable throwable = ex.getCause();
				while (throwable != null) {
					System.out.println("Cause: " + throwable);
					throwable = throwable.getCause();
				}
			}
		}
	}

	//read
	private void finderClientByName(String name) {
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelOS = new javax.swing.JPanel();
        jLabelNumeroOS = new javax.swing.JLabel();
        jTextFieldNumeroOS = new javax.swing.JTextField();
        jLabelDataOS = new javax.swing.JLabel();
        jTextFieldDataOS = new javax.swing.JTextField();
        jRadioButtonOrcamento = new javax.swing.JRadioButton();
        jRadioButtonOrdemServ = new javax.swing.JRadioButton();
        jLabelStatusOS = new javax.swing.JLabel();
        jComboBoxStatusOS = new javax.swing.JComboBox<>();
        jPanelCliente = new javax.swing.JPanel();
        jLabelPesquisaCliente = new javax.swing.JLabel();
        jTextFieldPesquisaCliente = new javax.swing.JTextField();
        jLabelClienteId = new javax.swing.JLabel();
        jTextFieldClienteId = new javax.swing.JTextField();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jSeparatorFormOS = new javax.swing.JSeparator();
        jLabelEquipamentoOS = new javax.swing.JLabel();
        jTextFieldEquipamentoOS = new javax.swing.JTextField();
        jLabelDefeitoOS = new javax.swing.JLabel();
        jTextFieldDefeitoOS = new javax.swing.JTextField();
        jLabelServicoOS = new javax.swing.JLabel();
        jTextFieldServicoOS = new javax.swing.JTextField();
        jLabelTecnicoOS = new javax.swing.JLabel();
        jTextFieldTecnicoOS = new javax.swing.JTextField();
        jLabelValorTotal = new javax.swing.JLabel();
        jTextFieldValorTotalOS = new javax.swing.JTextField();
        jButtonOSCreate = new javax.swing.JButton();
        jButtonOSRead = new javax.swing.JButton();
        jButtonOSUpdate = new javax.swing.JButton();
        jButtonOSDelete = new javax.swing.JButton();
        jButtonOSPrint = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Ordens de Servi;os");
        setPreferredSize(new java.awt.Dimension(650, 450));

        jPanelOS.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNumeroOS.setLabelFor(jTextFieldNumeroOS);
        jLabelNumeroOS.setText("Nº OS");

        jTextFieldNumeroOS.setEditable(false);
        jTextFieldNumeroOS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNumeroOS.setPreferredSize(new java.awt.Dimension(65, 22));

        jLabelDataOS.setLabelFor(jTextFieldDataOS);
        jLabelDataOS.setText("Data");

        jTextFieldDataOS.setEditable(false);
        jTextFieldDataOS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDataOS.setPreferredSize(new java.awt.Dimension(100, 22));

        buttonGroup1.add(jRadioButtonOrcamento);
        jRadioButtonOrcamento.setText("Orçamento");

        buttonGroup1.add(jRadioButtonOrdemServ);
        jRadioButtonOrdemServ.setText("Ordem Serviço");

        javax.swing.GroupLayout jPanelOSLayout = new javax.swing.GroupLayout(jPanelOS);
        jPanelOS.setLayout(jPanelOSLayout);
        jPanelOSLayout.setHorizontalGroup(
            jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOSLayout.createSequentialGroup()
                        .addGroup(jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumeroOS)
                            .addComponent(jTextFieldNumeroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDataOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDataOS)))
                    .addGroup(jPanelOSLayout.createSequentialGroup()
                        .addComponent(jRadioButtonOrcamento)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonOrdemServ)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOSLayout.setVerticalGroup(
            jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroOS)
                    .addComponent(jLabelDataOS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumeroOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOrcamento)
                    .addComponent(jRadioButtonOrdemServ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelStatusOS.setLabelFor(jComboBoxStatusOS);
        jLabelStatusOS.setText("Situação");

        jComboBoxStatusOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrega OK", "Orçamento Reprovado", "Aguardando Aprovação", "Aguardando Peça", "Abandonado pelo cliente", "Na bancada", "Retornou" }));

        jPanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cliente"));

        jLabelPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconSearch.png"))); // NOI18N
        jLabelPesquisaCliente.setLabelFor(jTextFieldPesquisaCliente);

        jTextFieldPesquisaCliente.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabelClienteId.setLabelFor(jTextFieldClienteId);
        jLabelClienteId.setText("* Id");

        jTextFieldClienteId.setEditable(false);
        jTextFieldClienteId.setPreferredSize(new java.awt.Dimension(100, 22));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ));
        jScrollPaneClientes.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPesquisaCliente)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelClienteId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPesquisaCliente))
                    .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClienteId)
                        .addComponent(jTextFieldClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelEquipamentoOS.setLabelFor(jTextFieldEquipamentoOS);
        jLabelEquipamentoOS.setText("* Equipamento");

        jTextFieldEquipamentoOS.setPreferredSize(new java.awt.Dimension(500, 22));

        jLabelDefeitoOS.setLabelFor(jTextFieldDefeitoOS);
        jLabelDefeitoOS.setText("* Defeito");

        jLabelServicoOS.setLabelFor(jTextFieldServicoOS);
        jLabelServicoOS.setText("Serviço");

        jLabelTecnicoOS.setLabelFor(jTextFieldTecnicoOS);
        jLabelTecnicoOS.setText("Técnico");

        jTextFieldTecnicoOS.setPreferredSize(new java.awt.Dimension(200, 22));

        jLabelValorTotal.setLabelFor(jTextFieldValorTotalOS);
        jLabelValorTotal.setText("Valor Total");

        jTextFieldValorTotalOS.setPreferredSize(new java.awt.Dimension(150, 22));

        jButtonOSCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconCreate.png"))); // NOI18N
        jButtonOSCreate.setToolTipText("Nova OS");
        jButtonOSCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOSCreate.setPreferredSize(new java.awt.Dimension(64, 64));

        jButtonOSRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconRead.png"))); // NOI18N
        jButtonOSRead.setToolTipText("Buscar OS");
        jButtonOSRead.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOSRead.setPreferredSize(new java.awt.Dimension(64, 64));

        jButtonOSUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconUpdate.png"))); // NOI18N
        jButtonOSUpdate.setToolTipText("Atualizar OS");
        jButtonOSUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOSUpdate.setPreferredSize(new java.awt.Dimension(64, 64));

        jButtonOSDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconDelete.png"))); // NOI18N
        jButtonOSDelete.setToolTipText("Excluir OS");
        jButtonOSDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOSDelete.setPreferredSize(new java.awt.Dimension(64, 64));

        jButtonOSPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconPrint.png"))); // NOI18N
        jButtonOSPrint.setToolTipText("Imprimir OS");
        jButtonOSPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOSPrint.setPreferredSize(new java.awt.Dimension(64, 64));

        jLabelInfo.setText("* Campos obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparatorFormOS)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonOSCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOSRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOSUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOSDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOSPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelInfo)
                        .addGap(0, 0, 0))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStatusOS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxStatusOS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanelOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEquipamentoOS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDefeitoOS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelServicoOS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTecnicoOS, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldTecnicoOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldValorTotalOS, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldServicoOS)
                            .addComponent(jTextFieldDefeitoOS)
                            .addComponent(jTextFieldEquipamentoOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonOSCreate, jButtonOSDelete, jButtonOSPrint, jButtonOSRead, jButtonOSUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStatusOS)
                            .addComponent(jComboBoxStatusOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorFormOS, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEquipamentoOS)
                    .addComponent(jTextFieldEquipamentoOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDefeitoOS)
                    .addComponent(jTextFieldDefeitoOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelServicoOS)
                    .addComponent(jTextFieldServicoOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTecnicoOS)
                    .addComponent(jTextFieldTecnicoOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorTotalOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonOSCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOSRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOSUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOSDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOSPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelInfo))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonOSCreate, jButtonOSDelete, jButtonOSPrint, jButtonOSRead, jButtonOSUpdate});

        setBounds(0, 0, 650, 450);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonOSCreate;
    private javax.swing.JButton jButtonOSDelete;
    private javax.swing.JButton jButtonOSPrint;
    private javax.swing.JButton jButtonOSRead;
    private javax.swing.JButton jButtonOSUpdate;
    private javax.swing.JComboBox<String> jComboBoxStatusOS;
    private javax.swing.JLabel jLabelClienteId;
    private javax.swing.JLabel jLabelDataOS;
    private javax.swing.JLabel jLabelDefeitoOS;
    private javax.swing.JLabel jLabelEquipamentoOS;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelNumeroOS;
    private javax.swing.JLabel jLabelPesquisaCliente;
    private javax.swing.JLabel jLabelServicoOS;
    private javax.swing.JLabel jLabelStatusOS;
    private javax.swing.JLabel jLabelTecnicoOS;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelOS;
    private javax.swing.JRadioButton jRadioButtonOrcamento;
    private javax.swing.JRadioButton jRadioButtonOrdemServ;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JSeparator jSeparatorFormOS;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldClienteId;
    private javax.swing.JTextField jTextFieldDataOS;
    private javax.swing.JTextField jTextFieldDefeitoOS;
    private javax.swing.JTextField jTextFieldEquipamentoOS;
    private javax.swing.JTextField jTextFieldNumeroOS;
    private javax.swing.JTextField jTextFieldPesquisaCliente;
    private javax.swing.JTextField jTextFieldServicoOS;
    private javax.swing.JTextField jTextFieldTecnicoOS;
    private javax.swing.JTextField jTextFieldValorTotalOS;
    // End of variables declaration//GEN-END:variables
}
