package br.com.infox.telas;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form TelaPrincipal
	 */
	public TelaPrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jLabeliconLog = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelDataHora = new javax.swing.JLabel();
        jLabelDateTime = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCadastroCliente = new javax.swing.JMenuItem();
        jMenuCadastroOrdemServico = new javax.swing.JMenuItem();
        jMenuCadastroUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuRelatorioServicos = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuAjudaSobre = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuOpcoesSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("X - Controle de Ordens de Serviço");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(955, 535));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane.setPreferredSize(new java.awt.Dimension(650, 450));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jLabeliconLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconLogo.png"))); // NOI18N

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUsuario.setText("Usuário:");

        jLabelUserName.setText("UserName");

        jLabelDataHora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDataHora.setText("Data e Hora:");

        jLabelDateTime.setText("dd/mm/YYYY  - HH : mm");

        jMenuCadastro.setText("Cadastro");

        jMenuCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconClient.png"))); // NOI18N
        jMenuCadastroCliente.setText("Cliente");
        jMenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroCliente);

        jMenuCadastroOrdemServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuCadastroOrdemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconOS.png"))); // NOI18N
        jMenuCadastroOrdemServico.setText("Ordem de Serviço");
        jMenuCadastro.add(jMenuCadastroOrdemServico);

        jMenuCadastroUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconUsers.png"))); // NOI18N
        jMenuCadastroUsuarios.setText("Usuários");
        jMenuCadastroUsuarios.setEnabled(false);
        jMenuCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCadastroUsuarios);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuRelatorio.setText("Relatório");
        jMenuRelatorio.setEnabled(false);

        jMenuRelatorioServicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuRelatorioServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconService.png"))); // NOI18N
        jMenuRelatorioServicos.setText("Serviços");
        jMenuRelatorio.add(jMenuRelatorioServicos);

        jMenuBarPrincipal.add(jMenuRelatorio);

        jMenuAjuda.setText("Ajuda");

        jMenuAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconInfo.png"))); // NOI18N
        jMenuAjudaSobre.setText("Sobre");
        jMenuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjudaSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuAjudaSobre);

        jMenuBarPrincipal.add(jMenuAjuda);

        jMenuOpcoes.setText("Opções");

        jMenuOpcoesSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuOpcoesSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icons/iconExit.png"))); // NOI18N
        jMenuOpcoesSair.setText("Sair");
        jMenuOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpcoesSairActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuOpcoesSair);

        jMenuBarPrincipal.add(jMenuOpcoes);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeliconLog)
                    .addComponent(jLabelDataHora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUserName)
                    .addComponent(jLabelDateTime))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataHora)
                            .addComponent(jLabelDateTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabeliconLog)))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
		String pattern = "dd/MM/yyyy  HH:mm";
		SimpleDateFormat dateFormat = new SimpleDateFormat(pattern,
			new Locale("pt", "BR"));
		jLabelDateTime.setText(dateFormat.format(new Date()));
    }//GEN-LAST:event_formWindowActivated

    private void jMenuOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpcoesSairActionPerformed
		int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Deseja encerrar o sistema?",
			"Atenção", JOptionPane.YES_NO_OPTION);
		if (showConfirmDialog == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
    }//GEN-LAST:event_jMenuOpcoesSairActionPerformed

    private void jMenuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjudaSobreActionPerformed
		TelaSobre sobre = new TelaSobre();
		sobre.setVisible(true);
    }//GEN-LAST:event_jMenuAjudaSobreActionPerformed

    private void jMenuCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroUsuariosActionPerformed
		TelaUsuario telaUsuario = new TelaUsuario();
		telaUsuario.setVisible(true);
		jDesktopPane.add(telaUsuario);
    }//GEN-LAST:event_jMenuCadastroUsuariosActionPerformed

    private void jMenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClienteActionPerformed
		TelaCliente telaCliente = new TelaCliente();
		telaCliente.setVisible(true);
		jDesktopPane.add(telaCliente);
    }//GEN-LAST:event_jMenuCadastroClienteActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new TelaPrincipal().setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabelDataHora;
    private javax.swing.JLabel jLabelDateTime;
    public static javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabeliconLog;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuItem jMenuAjudaSobre;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCadastroCliente;
    private javax.swing.JMenuItem jMenuCadastroOrdemServico;
    public static javax.swing.JMenuItem jMenuCadastroUsuarios;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenuItem jMenuOpcoesSair;
    public static javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenuItem jMenuRelatorioServicos;
    // End of variables declaration//GEN-END:variables
}
